dist: trusty
sudo: false
script:
  - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  - unzip terraform_0.11.8_linux_amd64.zip
deploy:
  - provider: script
    skip_cleanup: true
    script: bash terraform.sh apply -auto-approve
    on:
      tags: true
